version: "2"
linters:
  default: standard
  enable:
    - bidichk
    - containedctx
    - contextcheck
    - decorder
    - err13
    - errorlint
    - exhaustive
    - fatcontext
    - gocritic
    - gosec
    - govet
    - intrange
    - maintidx
    - modernize
    - nilnil
    - noctx
    - prealloc
    - recvcheck
    - sloglint
    - unparam
    - usestdlibvars
  settings:
    recvcheck:
      disable-builtin: false
      exclusions:
        - "*.TableName"
formatters:
  enable:
    - goimports
